### PR TITLE
Fixed all the todos from last commit

### PR DESCRIPTION
**Pull request by miker**
I fixed all of the todos we discussed. I have left 1. I hope this commit isn't to hard to merge. I see it can't be done automatically. Still trying to figure out the best workflow for this.

 TODO 1;
"Jail names should be descriptive. Jail names are limited to n characters, and can only be alphanumeric."                                                                            
I want to add a sentence about jail names, but wasn't sure if jail names can be, or should be descriptive, and what the jail name length limit is, or if names are limited to alphanumeric characters.

### CODE REVIEW

**Comment by miker** [comment]
Oops, I see what I did. I may be able to fix this.

**Comment by miker** [comment]
Looking again, I think the restoring a backup part should be rewritten. I'll be happy to do so if you give me the info to start from. I may be able to use what's there if need be.

**Comment by olevole** [comment]
> TODO 1;
> "Jail names should be descriptive. Jail names are limited to n characters, and can only be alphanumeric."
> I want to add a sentence about jail names, but wasn't sure if jail names can be, or should be 
> descriptive, and what the jail name length limit is, or if names are limited to alphanumeric characters.

I found only this information in the man page:
~~~
 name    The jail name.  This is an arbitrary string that identifies a
             jail (except it may not contain a ‘.’). 
~~~

It seems this is a good phrase) I could not find the maximum number of characters in jname in man.
By my test, jail name limited by 256 char. Therefore, I think we can not write about this

**Comment by miker** [comment]
Agreed about the character limit. I'll rework the info from the manpage into it. Only thing left for this page is restoring backups info (unless you already added it in) on my phone atm.

**Pull request merged**
